### ISSUE TITLE
window that already in new virtual desktop (VD) still can be moved to a new VD

### ISSUE THREAD

**Issue by azliR** [Ubiquitine/MACsimize6#3]
hi! this is a great script! but i get this buggy behaviour when launching vlc. first it is as expected with maximized window moved to the new virtual desktop (VD). but when i change it into full screen the window is moved. it seems the script cannot remember if that window is already moved or not. 

and another issue is when the window is close the VD is also closed even when there is still another window inside it.

and last issuue is everytime the VD is deleted, it keeps throwing me into the first VD. my understanding is at list it put me in the last VD or the nearest.

here is the example, sorry for a bad quality. but i really like this project. thank you so much!

[Screencast_20240801_161855.webm](https://github.com/user-attachments/assets/1a23f8b4-fa0c-4f44-9b31-9220defc757b)

**Comment by Ubiquitine** [comment]
From the initial assessment, VLC behaves a bit wired. From what I got via debugging, this is what happens:
1. VLC window is maximized and on a separate VD
2. Before going into a fullscreen VLC de-maximize the window (hence the window is being firstly restored to original VD)
3. Then VLC window finally changed into fullscreen and moved to a new VD

The script itself does have a functionality to check if a window is on its separate VD, but because VLC behaves this way, the script simply does what it supposed to do, giving the circumstances. 

For example Firefox or Chromium windows behave as expected, and when maximized window enters fullscreen (e.g. playing Youtube video in fullscreen), their windows do not moved to new VD. 
I also tested MPV and it behaves as expected, so it seems like VLC-specific behavior.

**Comment by azliR** [comment]
Thank you so much for your reply! Got it, so that's what happens. Well, I hope there's a solution for that. How about two other issues?

**Comment by Ubiquitine** [comment]
The second and the third issue is an expected behavior by design.
Each maximized/fullscreen window gets its VD and ones it is closed/unmaximized the VD is deleted and all windows on this VD are moved to the first VD, as well as the active VD is changed to the first one.
This script is intended to imitate OS X behavior.

**Comment by azliR** [comment]
Ah I see, I just find that a little annoying. Okay thank you for all the responses, closing this now.
